services:
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
    networks:
      - npc_net
  postgres:
    image: supernpc/pgsql:18
    networks:
      - npc_net
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  pgsql-ext-admin:
    image: supernpc/pgsql-ext-admin:latest
    container_name: pgsql-ext-admin
    networks:
      - npc_net
    environment:
      - TZ=Asia/Shanghai
      - spring.profiles.active=prd
      - feign.secret=123456 # 如果未使用微服务调用,固定默认值123456即可
      - password=123456 # 有使用加密功能,参考Jasypt实现
    ports:
      - 9019:9019
networks:
  npc_net:
    external: true