spring:
  data:
    redis:
      host: ENC(QI5VWUXF3u406eb9EFo2Wn2ig3eHFnp8RCPor4NYHW4dTFTwAJdJE5B7HCgvoIDk)
      port: 55119
      password: ENC(Wz7mBbtCZgpc/qWLRC3PUlfrlzUBq3qBnIZ/RRa05F/5p05VQj9pv0HtmLQ0F4UO)
      timeout: 3000
  datasource:
    dynamic:
      primary: my-pgsql
      strict: false
      datasource:
        my-pgsql:
          driver-class-name: org.postgresql.Driver
          url: ENC(RNK8TrdlR9uZeg2MmSoP34Rh6AmwLwoB2ilFX9S3JSfJ0KL3g+9anhHKiU+bQMVI14YOGLC3EB/eRYS05IzwNY7WtcJNmVjIvrkltoLcUepf6fiq5vgQiEA14V9wHehT)
          username: root
          password: ENC(Wz7mBbtCZgpc/qWLRC3PUlfrlzUBq3qBnIZ/RRa05F/5p05VQj9pv0HtmLQ0F4UO)