auto-table:
  # 开启自动建表
  enable: true
  record-sql:
    # 开启SQL记录
    enable: true
    # 当前版本（此处可保持与计划上线的版本号一致，方便管理SQL文件）
    version: 1.0.0
    # 记录到数据库（如果是多数据源，则会根据不同数据源，记录到不同的库）
    record-type: db

spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ENC(Wz7mBbtCZgpc/qWLRC3PUlfrlzUBq3qBnIZ/RRa05F/5p05VQj9pv0HtmLQ0F4UO)
      timeout: 3000
  datasource:
    dynamic:
      primary: my-pgsql
      strict: false
      datasource:
        my-pgsql:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://139.199.207.29:5432/pgsql-ext-admin
          username: root
          password: ENC(Wz7mBbtCZgpc/qWLRC3PUlfrlzUBq3qBnIZ/RRa05F/5p05VQj9pv0HtmLQ0F4UO)
