name: build pgsql-ext-spring

on:
  repository_dispatch:
    types: [ pgsql-ext-spring ]
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  build_modules: pgsql-ext-spring
  SPRING_PROFILES_ACTIVE: prd

jobs:
  build-code:
    name: 构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name:
        run: |
          # 初始化空仓库目录
          mkdir -p life-log
          cd life-log
          git init
          
          # 关闭Git默认分支提示（清理日志）
          git config --global init.defaultBranch main
          
          # 配置远程仓库（使用内置github.token访问私有仓库）
          git remote add origin https://${{ secrets.GIT_TOKEN }}@github.com/super-npc/life-log.git
          
          # 启用稀疏检出模式
          git config core.sparseCheckout true
          
          # 指定拉取settings.xml和settings-github.xml
          cat > .git/info/sparse-checkout << EOF
          /self/cicd/settings-github.xml
          EOF
          
          git pull origin main --depth 1

      # 构建 pgsql-ext-admin 并打包 Docker 镜像推送到 hub.docker.com
      # 说明: settings-github.xml 主要拉取项目依赖,参考: https://github.com/roy20021/pgmq-jdbc-client
      - name: 构建项目
        run: mvn package -pl pgsql-ext-admin -am -DskipTests -s /home/runner/work/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}/life-log/self/cicd/settings-github.xml ${{ env.MAVEN_OPTS }} -T 1C -U

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v6
        with:
          context: ./pgsql-ext-admin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            supernpc/pgsql-ext-admin:latest
            supernpc/pgsql-ext-admin:1.0-SNAPSHOT
          cache-from: type=gha
          cache-to: type=gha,mode=max
